fail

diff --git a/.github/workflows/pipeline CI CD.yaml b/.github/workflows/pipeline CI CD.yaml
--- a/.github/workflows/pipeline CI CD.yaml
+++ b/.github/workflows/pipeline CI CD.yaml
@@ -44,6 +44,12 @@ jobs:
                 SLACK_USERNAME: GitHub Actions
                 SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
 
+            - name: Fail the job if tests failed
+              if: steps.test.outcome == 'failure'
+              run: |
+                echo "❌ Unit tests failed! Stopping pipeline..."
+                exit 1
+
             - name: Slack Notification - Test Passed
               if: success()
               uses: rtCamp/action-slack-notify@v2
@@ -65,6 +71,7 @@ jobs:
     build-docker-image:
         runs-on: ubuntu-latest
         needs: unit-test
+        if: success()
         steps:
           - name: clone repo
             uses: actions/checkout@v7
@@ -94,6 +101,7 @@ jobs:
     deploy:
         runs-on: ubuntu-latest
         needs: build-docker-image
+        if: success()
         steps:
           - name: Execute remote SSH commands using password
             id: deploy
